### ISSUE TITLE
Почему tsrv?

### ISSUE THREAD

**Issue by coursar** [EduardMan/02.-Servlets-context-with-docker-#1]
https://github.com/EduardMan/02.-Servlets-context-with-docker-/blob/bd6644274b108a07d01828b70a23406e0e8387e8/.github/workflows/build.yml#L19

**Comment by EduardMan** [comment]
В инструкции [Docker Image Publishing](https://github.com/coursar/manuals/tree/master/01_docker) вы написали 'в качестве имени образа можете оставить `tsrv`'. Я и оставил) Нужно поменять?

![2021-05-09_20-38-03](https://user-images.githubusercontent.com/5735110/117581635-96a13700-b106-11eb-8820-e86ae536f1d1.png)
